import { anyApi } from 'convex/server';

// Typed API is generated by Convex in convex/_generated/api when a deployment is configured.
// We use anyApi here so the app keeps compiling before the first `convex dev` setup.
export const multiplayerApi = anyApi;
